### ISSUE TITLE
--debug option

### ISSUE THREAD

**Issue by ramaniak** [cancerit/cgpCaVEManWrapper#29]
Hello,
I was wondering how to invoke the debug parameter when executing the caveman-wrapper? Specifically, I am trying to get estep to run with the debug option look at every position considered. 

```
-s  --debug     Adds an extra output to a debug file. Every base analysed has an output
```

The '-s' flag is confused by the caveman wrapper as species and therefore throws an error.

thanks
Arun

**Comment by keiranmraine** [comment]
Resolved by #30

**Comment by ramaniak** [comment]
Hi Keiran,
I was wondering what the solution to my issue is? 

thanks
Arun

**Comment by keiranmraine** [comment]
Have you viewed the issue on GitHub (for full history)?  We have exposed the value to the wrapper code and are in the process of testing the release.

**Comment by ramaniak** [comment]
Apologies, I did not. Thanks for taking care of this.

Arun
