### ISSUE TITLE
Pre-release tag for fragment analysis

### ISSUE THREAD

**Issue by keiranmraine** [cancerit/cgpCaVEManWrapper#35]
- [x] Create `feature/overlapping_reads
- [x] Link to the pre-release from https://github.com/cancerit/CaVEMan/issues/76.
- [x] Address #33
- [x] Create pre-release

**Comment by drjsanger** [comment]
Testing #33, then ready to go.

**Comment by drjsanger** [comment]
@keiranmraine [1.30.0-rc1](https://github.com/cancerit/cgpCaVEManWrapper/archive/1.13.0-rc1.tar.gz) created

**Comment by drjsanger** [comment]
Released in version [1.13.0](https://github.com/cancerit/cgpCaVEManWrapper/releases/tag/1.13.0)
