### ISSUE TITLE
Missing run instructions

### ISSUE THREAD

**Issue by winni2k** [cancerit/cgpCaVEManWrapper#50]
How do I run this tool?

**Comment by winni2k** [comment]
I'm still experimenting, but It looks like something like this would work with singularity:

```bash
CGPWRAPPER_VERSION=1.16.0

singularity pull cgpcavemanwrapper-$CGPWRAPPER_VERSION.sif docker://quay.io/wtsicgp/cgpcavemanwrapper:$CGPWRAPPER_VERSION
singularity exec cgpcavemanwrapper-$CGPWRAPPER_VERSION.sif caveman.pl --help
```

**Comment by keiranmraine** [comment]
Please see the wiki and command line help:

https://github.com/cancerit/cgpCaVEManWrapper/wiki

Docker and singularity are known to work.
